# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a66ac36a578965d404e52d22a92936a9ee71bffb89b1cde28346f66a59cb6f2383f94c3596581803a19b7bf965bb8d815061ed49a1f2381d7b26660c32b6e2b2

test:
  secret_key_base: 08a74f4598ed5fd22a549f1bf6fb2371afe3f31e5cb6c855514eb70c1267ee39289fc44b6ba8d6e4d8db1436525ccac54bc613fc09c5c2ec62eb1bb2b705cf63

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
